name: Deploy

on: workflow_dispatch

jobs: 
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.PRIVATE_KEY }}
            port: ${{ secrets.PORT }}
            script: cd /opt/codest-open/ && ./deploy.sh
